### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by danharper** [gajus/eslint-plugin-flowtype#120]
https://greenkeeper.io/

@gajus could you enable this for the repo? Will help us know as soon as the tests fail due to dependency changes. (I would, but you need admin access to the repo).

e.g. the latest version of Babylon now prevents invalid Flow syntax - which breaks our tests for `valid-syntax` as it's now a compiler error, not lint. (I guess for that, I'm just going to remove the tests and mark the rule deprecated).

**Comment by gajus** [comment]
I have tried Greenkeeper once. I disliked it a lot because it was producing 20-30 notifications a day on a large project, per project. You can see how that wouldn't work with 100+ projects that I look after.

I have enabled it for another test. But I am keeping the right to disable it in the future. :-)
