### ISSUE TITLE
Pull in Flow-specific rules from eslint-plugin-babel

### ISSUE THREAD

**Issue by taion** [gajus/eslint-plugin-flowtype#141]
Ref https://github.com/gajus/eslint-plugin-flowtype/issues/40#issuecomment-244817855, https://github.com/babel/eslint-plugin-babel/issues/93#issuecomment-255808138

In addition to the obvious `babel/flow-object-type`, the following rules in eslint-plugin-babel:
- `babel/array-bracket-spacing`
- `babel/arrow-parens`

Only make a difference now when using Flow. (The latter because ESLint now supports `async`/`await` natively)

I think it would make sense to pull in those rules here – I found it confusing that the rule I wanted to get rid of spurious warnings on arrow parens when using type annotations was in eslint-plugin-babel rather than here.

**Comment by danharper** [comment]
Hm, I'm kind of unsure about the others.

I see this plugin as providing lint rules _specific_ to Flow's syntax, whereas `eslint-plugin-babel` provides replacement rules to the core ESLint ones until the proposal reaches stage 4.

Since ESLint is now officially supporting simple type annotations in the AST, those 2 rules can probably be upstreamed back to ESLint.

**Comment by taion** [comment]
Ah, I didn't know that. Thanks.

**Comment by danharper** [comment]
Looks like there's a PR open for `arrow-parens` too :) https://github.com/eslint/eslint/pull/7436

**Comment by taion** [comment]
Thanks. I opened https://github.com/eslint/eslint/pull/7445 to fix `array-bracket-spacing` as well.
