### ISSUE TITLE
Unexpected token when using generics

### ISSUE THREAD

**Issue by favio41** [gajus/eslint-plugin-flowtype#378]
Hi, trying the generics and using a basic example from the flow.org website:
```
//@flow
class GenericClass<T> {}
const c = new GenericClass<number>();
```
I get the following error:
```
3:36  error  Parsing error: Unexpected token
```
Using versions: 
- eslint-plugin-flowtype@3.2.0
- babel-preset-flow@6.23.0

**Comment by pnevyk** [comment]
Hi, this error is not caused by `eslint-plugin-flowtype` because it's a syntax error thrown from the parser. According to [this](https://github.com/babel/babel/issues/8332) issue, this syntax is supported by Babel v7. Try to upgrade appropriate babel packages (namely babel core, and perhaps flow preset, maybe others) to the latest versions and it should start to work.
