### ISSUE TITLE
Question: flowtype/require-return-type and render method in React components

### ISSUE THREAD

**Issue by psawaya** [gajus/eslint-plugin-flowtype#83]
I'm curious what the recommended way to handle return types for `render` methods of React Components is.

I'm getting `warning  Missing return type annotation                 flowtype/require-return-type` warnings for each `render` method, and I'm not totally clear what return type to provide

Apologies for the noob question! But I couldn't find a clear answer elsewhere. The [React example](https://flowtype.org/docs/react.html) in the Flow docs don't include return types for `render`

**Comment by danharper** [comment]
I _think_ it's `React.Element` or `React$Element`

**Comment by damienleroux** [comment]
Is there any way to avoid having to declare the return type of React `render()` method? I don't know a use case where I'll need to be notified if a React component return well jsx or null. React already handle the situation for us and I dont want to add on every `render()` : `React.Element<any>`.

Any solution or hack for this? :)

**Comment by JasonHenson** [comment]
yeah, would be nice to ignore this method and other React methods like shouldComponentUpdate, etc.

**Comment by Chaoste** [comment]
I tried excluding render methods by adding "excludeMatching": ["render"] for the eslint rule flowtype/require-return-type  (I also tried "^render$") but it wont work for class methods.

I gues this is a bug because it works only if I write "excludeMatching": ["undefined"]. So it looks like class methods not correctly parsed.
